config/routes.rb
Gitlab::Application.routes.draw do
  get 'search' => "search#show"

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server.new, at: '/info/resque'

  get 'help' => 'help#index'
  get 'help/permissions' => 'help#permissions'
  get 'help/workflow' => 'help#workflow'
  get 'help/web_hooks' => 'help#web_hooks'

  namespace :admin do
    resources :users do 
      member do 
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, :constraints => { :id => /[^\/]+/ } do 
      member do 
        get :team
        put :team_update
      end
    end
    resources :team_members, :only => [:edit, :update, :destroy]
    get 'emails', :to => 'mailer#preview'
    get 'mailer/preview_note'
    get 'mailer/preview_user_new'
    get 'mailer/preview_issue_new'
    root :to => "dashboard#index"
  end

  get "errors/githost"
  get "profile/password", :to => "profile#password"
  put "profile/password", :to => "profile#password_update"
  get "profile/token", :to => "profile#token"
  put "profile/reset_private_token", :to => "profile#reset_private_token"
  get "profile", :to => "profile#show"
  get "profile/design", :to => "profile#design"
  put "profile/update", :to => "profile#update"

  get "dashboard/issues", :to => "dashboard#issues"
  get "dashboard/merge_requests", :to => "dashboard#merge_requests"

  resources :projects, :constraints => { :id => /[^\/]+/ }, :only => [:new, :create, :index]
  resources :keys

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks }

  resources :projects, :constraints => { :id => /[^\/]+/ }, :except => [:new, :create, :index], :path => "/" do
    member do
      get "team"
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, :only => [:show, :edit, :destroy, :create] do
      member do
        get "history"        
      end
    end

    resource :repository do 
      member do 
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, :only => [:index, :create, :destroy]

    resources :refs, :only => [], :path => "/" do 
      collection do 
        get "switch"
      end

      member do 
        get "tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }
        get "blob", 
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }


        # tree viewer
        get "tree/:path" => "refs#tree",
          :as => :tree_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }

        # blame
        get "blame/:path" => "refs#blame",
          :as => :blame_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }
      end
    end

    resources :merge_requests do 
      member do 
        get :diffs
        get :automerge
        get :automerge_check
      end

      collection do 
        get :branch_from
        get :branch_to
      end
    end
    
    resources :snippets
    resources :hooks, :only => [:index, :create, :destroy] do 
      member do 
        get :test
      end
    end
    resources :commits do 
      collection do 
        get :compare
      end
    end
    resources :team_members
    resources :milestones
    resources :issues do
      collection do
        post  :sort
        get   :search
      end
    end
    resources :notes, :only => [:index, :create, :destroy]
  end
  root :to => "projects#index"
end

app/models/project.rb
require "grit"

class Project < ActiveRecord::Base
  include Repository
  include GitPush
  include Authority
  include Team

  #
  # Relations
  # 
  belongs_to :owner, :class_name => "User"
  has_many :users,          :through => :users_projects
  has_many :events,         :dependent => :destroy
  has_many :merge_requests, :dependent => :destroy
  has_many :issues,         :dependent => :destroy, :order => "position"
  has_many :milestones,     :dependent => :destroy
  has_many :users_projects, :dependent => :destroy
  has_many :notes,          :dependent => :destroy
  has_many :snippets,       :dependent => :destroy
  has_many :deploy_keys,    :dependent => :destroy, :foreign_key => "project_id", :class_name => "Key"
  has_many :web_hooks,      :dependent => :destroy
  has_many :wikis,          :dependent => :destroy
  has_many :protected_branches, :dependent => :destroy

  # 
  # Protected attributes
  #
  attr_protected :private_flag, :owner_id

  # 
  # Scopes
  #
  scope :public_only, where(:private_flag => false)
  scope :without_user, lambda { |user|  where("id not in (:ids)", :ids => user.projects.map(&:id) ) }

  def self.active
    joins(:issues, :notes, :merge_requests).order("issues.created_at, notes.created_at, merge_requests.created_at DESC")
  end

  def self.search query
    where("name like :query or code like :query or path like :query", :query => "%#{query}%")
  end

  def self.create_by_user(params, user)
    project = Project.new params

    Project.transaction do
      project.owner = user

      project.save!

      # Add user as project master
      project.users_projects.create!(:project_access => UsersProject::MASTER, :user => user)

      # when project saved no team member exist so
      # project repository should be updated after first user add
      project.update_repository
    end

    project
  end

  #
  # Validations
  #
  validates :name,
            :uniqueness => true,
            :presence => true,
            :length   => { :within => 0..255 }

  validates :path,
            :uniqueness => true,
            :presence => true,
            :format => { :with => /^[a-zA-Z0-9_\-\.]*$/,
                         :message => "only letters, digits & '_' '-' '.' allowed" },
            :length   => { :within => 0..255 }

  validates :description,
            :length   => { :within => 0..2000 }

  validates :code,
            :presence => true,
            :uniqueness => true,
            :format => { :with => /^[a-zA-Z0-9_\-\.]*$/,
                         :message => "only letters, digits & '_' '-' '.' allowed"  },
            :length   => { :within => 1..255 }

  validates :owner, :presence => true
  validate :check_limit
  validate :repo_name

  def check_limit
    unless owner.can_create_project?
      errors[:base] << ("Your own projects limit is #{owner.projects_limit}! Please contact administrator to increase it")
    end
  rescue
    errors[:base] << ("Cant check your ability to create project")
  end

  def repo_name
    if path == "gitolite-admin"
      errors.add(:path, " like 'gitolite-admin' is not allowed")
    end
  end
  
  def self.access_options
    UsersProject.access_roles
  end

  def to_param
    code
  end

  def web_url
    [GIT_HOST['host'], code].join("/")
  end

  def common_notes
    notes.where(:noteable_type => ["", nil]).inc_author_project
  end

  def build_commit_note(commit)
    notes.new(:noteable_id => commit.id, :noteable_type => "Commit")
  end

  def commit_notes(commit)
    notes.where(:noteable_id => commit.id, :noteable_type => "Commit", :line_code => nil)
  end

  def commit_line_notes(commit)
    notes.where(:noteable_id => commit.id, :noteable_type => "Commit").where("line_code is not null")
  end

  def public?
    !private_flag
  end

  def private?
    private_flag
  end

  def last_activity
    events.last || nil
  end

  def last_activity_date
    if events.last
      events.last.created_at
    else
      updated_at
    end
  end

  def project_id
    self.id
  end
end

# == Schema Information
#
# Table name: projects
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  path                   :string(255)
#  description            :text
#  created_at             :datetime
#  updated_at             :datetime
#  private_flag           :boolean         default(TRUE), not null
#  code                   :string(255)
#  owner_id               :integer
#  default_branch         :string(255)     default("master"), not null
#  issues_enabled         :boolean         default(TRUE), not null
#  wall_enabled           :boolean         default(TRUE), not null
#  merge_requests_enabled :boolean         default(TRUE), not null
#  wiki_enabled           :boolean         default(TRUE), not null
#

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  def index
    @admin_projects = Project.page(params[:page])
  end

  def show
    @admin_project = Project.find_by_code(params[:id])

    @users = if @admin_project.users.empty?
               User
             else
               User.not_in_project(@admin_project)
             end.all
  end

  def new
    @admin_project = Project.new
  end

  def edit
    @admin_project = Project.find_by_code(params[:id])
  end

  def team_update
    @admin_project = Project.find_by_code(params[:id])

    UsersProject.bulk_import(
      @admin_project, 
      params[:user_ids],
      params[:project_access]
    )

    @admin_project.update_repository

    redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
  end

  def create
    @admin_project = Project.new(params[:project])
    @admin_project.owner = current_user

    if @admin_project.save
      redirect_to [:admin, @admin_project], notice: 'Project was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @admin_project = Project.find_by_code(params[:id])

    owner_id = params[:project].delete(:owner_id)

    if owner_id 
      @admin_project.owner = User.find(owner_id)
    end

    if @admin_project.update_attributes(params[:project])
      redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @admin_project = Project.find_by_code(params[:id])
    @admin_project.destroy

    redirect_to admin_projects_url
  end
end

app/controllers/projects_controller.rb
require File.join(Rails.root, 'lib', 'graph_commit')

class ProjectsController < ApplicationController
  before_filter :project, :except => [:index, :new, :create]
  layout :determine_layout

  # Authorize
  before_filter :add_project_abilities
  before_filter :authorize_read_project!, :except => [:index, :new, :create]
  before_filter :authorize_admin_project!, :only => [:edit, :update, :destroy]
  before_filter :require_non_empty_project, :only => [:blob, :tree, :graph]

  def index
    @projects = current_user.projects.includes(:events).order("events.created_at DESC")
    @projects = @projects.page(params[:page]).per(40)
    @events = Event.where(:project_id => current_user.projects.map(&:id)).recent.limit(20)

    respond_to do |format|
      format.html
      format.atom { render :layout => false }
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.create_by_user(params[:project], current_user)

    respond_to do |format|
      if @project.valid?
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  rescue Gitlab::Gitolite::AccessDenied
    render :js => "location.href = '#{errors_githost_path}'" and return
  rescue StandardError => ex
    @project.errors.add(:base, "Cant save project. Please try again later")
    respond_to do |format|
      format.html { render action: "new" }
      format.js
    end
  end

  def update
    respond_to do |format|
      if project.update_attributes(params[:project])
        format.html { redirect_to edit_project_path(project), :notice => 'Project was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def show
    limit = (params[:limit] || 20).to_i
    @events = @project.events.recent.limit(limit)

    respond_to do |format|
      format.html do
         if @project.repo_exists? && @project.has_commits?
           render :show
         else
           render "projects/empty"
         end
      end
    end
  end

  def files
    @notes = @project.notes.where("attachment != 'NULL'").order("created_at DESC").limit(100)
  end

  #
  # Wall
  #

  def wall
    return render_404 unless @project.wall_enabled
    @note = Note.new

    respond_to do |format|
      format.html
    end
  end

  def graph
    @days_json, @commits_json = GraphCommit.to_graph(project)
  end

  def destroy
    # Disable the UsersProject update_repository call, otherwise it will be
    # called once for every person removed from the project
    UsersProject.skip_callback(:destroy, :after, :update_repository)
    project.destroy
    UsersProject.set_callback(:destroy, :after, :update_repository)

    respond_to do |format|
      format.html { redirect_to projects_url }
    end
  end

  protected

  def project
    @project ||= Project.find_by_code(params[:id])
    @project || render_404
  end

  def determine_layout
    if @project && !@project.new_record?
      "project"
    else
      "application"
    end
  end
end

app/views/admin/projects/_form.html.haml
= form_for [:admin, @admin_project] do |f|
  -if @admin_project.errors.any?
    .alert-message.block-message.error
      %ul
        - @admin_project.errors.full_messages.each do |msg|
          %li= msg

  .clearfix
    = f.label :name
    .input= f.text_field :name
  .clearfix
    = f.label :path do
      Path
    .input
      .input-prepend
        %span.add-on= "#{GIT_HOST["git_user"]}@#{GIT_HOST["host"]}:"
        = f.text_field :path, :placeholder => "example_project", :disabled => !@admin_project.new_record?
  .clearfix
    = f.label :code do
      Code
    .input
      .input-prepend
        %span.add-on= web_app_url
        = f.text_field :code, :placeholder => "example"

  - unless @admin_project.new_record?
    .clearfix
      = f.label :owner_id
      .input= f.select :owner_id, User.all.map { |user| [user.name, user.id] }

    - if @admin_project.repo_exists?
      .clearfix
        = f.label :default_branch, "Default Branch"
        .input= f.select(:default_branch, @admin_project.heads.map(&:name), {}, :style => "width:210px;")

    .well
      %h5 Features

      .clearfix
        = f.label :issues_enabled, "Issues"
        .input= f.check_box :issues_enabled

      .clearfix
        = f.label :merge_requests_enabled, "Merge Requests"
        .input= f.check_box :merge_requests_enabled

      .clearfix
        = f.label :wall_enabled, "Wall"
        .input= f.check_box :wall_enabled

  .clearfix
    = f.label :description
    .input= f.text_area :description, :class => "xxlarge"
  .clear
  %br
  .actions
    = f.submit 'Save', :class => "btn primary"
    = link_to 'Cancel', [:admin, @admin_project], :class => "btn"
    - unless @admin_project.new_record?
      = link_to 'Destroy', [:admin, @admin_project], :confirm => 'Are you sure?', :method => :delete, :class => "btn danger right"

:javascript
  $(function(){
    $('#project_owner_id').chosen();
    new Projects();
  })

app/views/admin/projects/edit.html.haml
%h3= @admin_project.name
%hr
= render 'form'

app/views/admin/projects/index.html.haml
%h3
  Projects
  = link_to 'New Project', new_admin_project_path, :class => "btn small right"
%br
%table.admin-table
  %thead
    %th Name
    %th Path
    %th Team Members
    %th Post Receive
    %th Last Commit
    %th
    %th

  - @admin_projects.each do |project|
    %tr
      %td= link_to project.name, [:admin, project]
      %td= project.path
      %td= project.users_projects.count
      %td= check_box_tag :post_receive_file, 1, project.has_post_receive_file?, :disabled => true
      %td= last_commit(project)
      %td= link_to 'Edit', edit_admin_project_path(project), :id => "edit_#{dom_id(project)}", :class => "btn small"
      %td= link_to 'Destroy', [:admin, project], :confirm => 'Are you sure?', :method => :delete, :class => "btn small danger"
= paginate @admin_projects, :theme => "admin"

app/views/admin/projects/new.html.haml
%h2 New project
%hr
= render 'form'

app/views/admin/projects/show.html.haml
%h3
  = @admin_project.name
  = link_to 'Edit', edit_admin_project_path(@admin_project), :class => "btn right small"

%br
%table.zebra-striped.table-bordered
  %tr
    %td
      %b
        Name:
    %td
      = @admin_project.name
  %tr
    %td
      %b
        Code:
    %td
      = @admin_project.code
  %tr
    %td
      %b
        Path:
    %td
      = @admin_project.path
  %tr
    %td
      %b
        Description:
    %td
      = @admin_project.description
  %tr
    %td
      %b
        Post Receive File:
    %td
      = check_box_tag :post_receive_file, 1, @admin_project.has_post_receive_file?, :disabled => true
%br
%h3
  Team
  %small
    (#{@admin_project.users_projects.count})
%br
%table.zebra-striped.table-bordered
  %thead
    %tr
      %th Name
      %th Project Access
      %th Repository Access
      %th

  - @admin_project.users_projects.each do |tm|
    %tr
      %td
        = link_to tm.user_name, admin_user_path(tm.user)
      %td= select_tag :tm_project_access, options_for_select(Project.access_options, tm.project_access), :class => "medium project-access-select", :disabled => :disabled
      %td= link_to 'Edit Access', edit_admin_team_member_path(tm), :class => "btn small"
      %td= link_to 'Remove from team', admin_team_member_path(tm), :confirm => 'Are you sure?', :method => :delete, :class => "btn danger small"

%br
%h3 Add new team member
%br
= form_tag team_update_admin_project_path(@admin_project), :class => "bulk_import", :method => :put  do
  %table.zebra-striped.table-bordered
    %thead
      %tr
        %th Users
        %th Project Access:

    %tr
      %td= select_tag :user_ids, options_from_collection_for_select(@users , :id, :name),  :multiple => true
      %td= select_tag :project_access, options_for_select(Project.access_options), :class => "project-access-select"

    %tr
      %td= submit_tag 'Add', :class => "btn primary"
      %td
        Read more about project permissions
        %strong= link_to "here", help_permissions_path, :class => "vlink"

:css
  form select {
    width:150px;
  }

  #user_ids {
    width:300px;
  }

:javascript
  $('select#user_ids').chosen();
  $('select#repo_access').chosen();
  $('select#project_access').chosen();