config/routes.rb
Gitlab::Application.routes.draw do
  get 'search' => "search#show"

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server.new, at: '/info/resque'

  get 'help' => 'help#index'
  get 'help/permissions' => 'help#permissions'
  get 'help/workflow' => 'help#workflow'
  get 'help/web_hooks' => 'help#web_hooks'

  namespace :admin do
    resources :users do 
      member do 
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, :constraints => { :id => /[^\/]+/ } do 
      member do 
        get :team
        put :team_update
      end
    end
    resources :team_members, :only => [:edit, :update, :destroy]
    get 'emails', :to => 'mailer#preview'
    get 'mailer/preview_note'
    get 'mailer/preview_user_new'
    get 'mailer/preview_issue_new'
    root :to => "dashboard#index"
  end

  get "errors/githost"
  get "profile/password", :to => "profile#password"
  put "profile/password", :to => "profile#password_update"
  get "profile/token", :to => "profile#token"
  put "profile/reset_private_token", :to => "profile#reset_private_token"
  get "profile", :to => "profile#show"
  get "profile/design", :to => "profile#design"
  put "profile/update", :to => "profile#update"

  get "dashboard/issues", :to => "dashboard#issues"
  get "dashboard/merge_requests", :to => "dashboard#merge_requests"

  resources :projects, :constraints => { :id => /[^\/]+/ }, :only => [:new, :create, :index]
  resources :keys

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks }

  resources :projects, :constraints => { :id => /[^\/]+/ }, :except => [:new, :create, :index], :path => "/" do
    member do
      get "team"
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, :only => [:show, :edit, :destroy, :create] do
      member do
        get "history"        
      end
    end

    resource :repository do 
      member do 
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, :only => [:index, :create, :destroy]

    resources :refs, :only => [], :path => "/" do 
      collection do 
        get "switch"
      end

      member do 
        get "tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }
        get "blob", 
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }


        # tree viewer
        get "tree/:path" => "refs#tree",
          :as => :tree_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }

        # blame
        get "blame/:path" => "refs#blame",
          :as => :blame_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }
      end
    end

    resources :merge_requests do 
      member do 
        get :diffs
        get :automerge
        get :automerge_check
      end

      collection do 
        get :branch_from
        get :branch_to
      end
    end
    
    resources :snippets
    resources :hooks, :only => [:index, :create, :destroy] do 
      member do 
        get :test
      end
    end
    resources :commits do 
      collection do 
        get :compare
      end
    end
    resources :team_members
    resources :milestones
    resources :issues do
      collection do
        post  :sort
        get   :search
      end
    end
    resources :notes, :only => [:index, :create, :destroy]
  end
  root :to => "projects#index"
end

app/models/project.rb
require "grit"

class Project < ActiveRecord::Base
  include Repository
  include GitPush
  include Authority
  include Team

  #
  # Relations
  # 
  belongs_to :owner, :class_name => "User"
  has_many :users,          :through => :users_projects
  has_many :events,         :dependent => :destroy
  has_many :merge_requests, :dependent => :destroy
  has_many :issues,         :dependent => :destroy, :order => "position"
  has_many :milestones,     :dependent => :destroy
  has_many :users_projects, :dependent => :destroy
  has_many :notes,          :dependent => :destroy
  has_many :snippets,       :dependent => :destroy
  has_many :deploy_keys,    :dependent => :destroy, :foreign_key => "project_id", :class_name => "Key"
  has_many :web_hooks,      :dependent => :destroy
  has_many :wikis,          :dependent => :destroy
  has_many :protected_branches, :dependent => :destroy

  # 
  # Protected attributes
  #
  attr_protected :private_flag, :owner_id

  # 
  # Scopes
  #
  scope :public_only, where(:private_flag => false)
  scope :without_user, lambda { |user|  where("id not in (:ids)", :ids => user.projects.map(&:id) ) }

  def self.active
    joins(:issues, :notes, :merge_requests).order("issues.created_at, notes.created_at, merge_requests.created_at DESC")
  end

  def self.search query
    where("name like :query or code like :query or path like :query", :query => "%#{query}%")
  end

  def self.create_by_user(params, user)
    project = Project.new params

    Project.transaction do
      project.owner = user

      project.save!

      # Add user as project master
      project.users_projects.create!(:project_access => UsersProject::MASTER, :user => user)

      # when project saved no team member exist so
      # project repository should be updated after first user add
      project.update_repository
    end

    project
  end

  #
  # Validations
  #
  validates :name,
            :uniqueness => true,
            :presence => true,
            :length   => { :within => 0..255 }

  validates :path,
            :uniqueness => true,
            :presence => true,
            :format => { :with => /^[a-zA-Z0-9_\-\.]*$/,
                         :message => "only letters, digits & '_' '-' '.' allowed" },
            :length   => { :within => 0..255 }

  validates :description,
            :length   => { :within => 0..2000 }

  validates :code,
            :presence => true,
            :uniqueness => true,
            :format => { :with => /^[a-zA-Z0-9_\-\.]*$/,
                         :message => "only letters, digits & '_' '-' '.' allowed"  },
            :length   => { :within => 1..255 }

  validates :owner, :presence => true
  validate :check_limit
  validate :repo_name

  def check_limit
    unless owner.can_create_project?
      errors[:base] << ("Your own projects limit is #{owner.projects_limit}! Please contact administrator to increase it")
    end
  rescue
    errors[:base] << ("Cant check your ability to create project")
  end

  def repo_name
    if path == "gitolite-admin"
      errors.add(:path, " like 'gitolite-admin' is not allowed")
    end
  end
  
  def self.access_options
    UsersProject.access_roles
  end

  def to_param
    code
  end

  def web_url
    [GIT_HOST['host'], code].join("/")
  end

  def common_notes
    notes.where(:noteable_type => ["", nil]).inc_author_project
  end

  def build_commit_note(commit)
    notes.new(:noteable_id => commit.id, :noteable_type => "Commit")
  end

  def commit_notes(commit)
    notes.where(:noteable_id => commit.id, :noteable_type => "Commit", :line_code => nil)
  end

  def commit_line_notes(commit)
    notes.where(:noteable_id => commit.id, :noteable_type => "Commit").where("line_code is not null")
  end

  def public?
    !private_flag
  end

  def private?
    private_flag
  end

  def last_activity
    events.last || nil
  end

  def last_activity_date
    if events.last
      events.last.created_at
    else
      updated_at
    end
  end

  def project_id
    self.id
  end
end

# == Schema Information
#
# Table name: projects
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  path                   :string(255)
#  description            :text
#  created_at             :datetime
#  updated_at             :datetime
#  private_flag           :boolean         default(TRUE), not null
#  code                   :string(255)
#  owner_id               :integer
#  default_branch         :string(255)     default("master"), not null
#  issues_enabled         :boolean         default(TRUE), not null
#  wall_enabled           :boolean         default(TRUE), not null
#  merge_requests_enabled :boolean         default(TRUE), not null
#  wiki_enabled           :boolean         default(TRUE), not null
#

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  def index
    @admin_projects = Project.page(params[:page])
  end

  def show
    @admin_project = Project.find_by_code(params[:id])

    @users = if @admin_project.users.empty?
               User
             else
               User.not_in_project(@admin_project)
             end.all
  end

  def new
    @admin_project = Project.new
  end

  def edit
    @admin_project = Project.find_by_code(params[:id])
  end

  def team_update
    @admin_project = Project.find_by_code(params[:id])

    UsersProject.bulk_import(
      @admin_project, 
      params[:user_ids],
      params[:project_access]
    )

    @admin_project.update_repository

    redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
  end

  def create
    @admin_project = Project.new(params[:project])
    @admin_project.owner = current_user

    if @admin_project.save
      redirect_to [:admin, @admin_project], notice: 'Project was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @admin_project = Project.find_by_code(params[:id])

    owner_id = params[:project].delete(:owner_id)

    if owner_id 
      @admin_project.owner = User.find(owner_id)
    end

    if @admin_project.update_attributes(params[:project])
      redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @admin_project = Project.find_by_code(params[:id])
    @admin_project.destroy

    redirect_to admin_projects_url
  end
end

app/controllers/projects_controller.rb
require File.join(Rails.root, 'lib', 'graph_commit')

class ProjectsController < ApplicationController
  before_filter :project, :except => [:index, :new, :create]
  layout :determine_layout

  # Authorize
  before_filter :add_project_abilities
  before_filter :authorize_read_project!, :except => [:index, :new, :create]
  before_filter :authorize_admin_project!, :only => [:edit, :update, :destroy]
  before_filter :require_non_empty_project, :only => [:blob, :tree, :graph]

  def index
    @projects = current_user.projects.includes(:events).order("events.created_at DESC")
    @projects = @projects.page(params[:page]).per(40)
    @events = Event.where(:project_id => current_user.projects.map(&:id)).recent.limit(20)

    respond_to do |format|
      format.html
      format.atom { render :layout => false }
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.create_by_user(params[:project], current_user)

    respond_to do |format|
      if @project.valid?
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  rescue Gitlab::Gitolite::AccessDenied
    render :js => "location.href = '#{errors_githost_path}'" and return
  rescue StandardError => ex
    @project.errors.add(:base, "Cant save project. Please try again later")
    respond_to do |format|
      format.html { render action: "new" }
      format.js
    end
  end

  def update
    respond_to do |format|
      if project.update_attributes(params[:project])
        format.html { redirect_to edit_project_path(project), :notice => 'Project was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def show
    limit = (params[:limit] || 20).to_i
    @events = @project.events.recent.limit(limit)

    respond_to do |format|
      format.html do
         if @project.repo_exists? && @project.has_commits?
           render :show
         else
           render "projects/empty"
         end
      end
    end
  end

  def files
    @notes = @project.notes.where("attachment != 'NULL'").order("created_at DESC").limit(100)
  end

  #
  # Wall
  #

  def wall
    return render_404 unless @project.wall_enabled
    @note = Note.new

    respond_to do |format|
      format.html
    end
  end

  def graph
    @days_json, @commits_json = GraphCommit.to_graph(project)
  end

  def destroy
    # Disable the UsersProject update_repository call, otherwise it will be
    # called once for every person removed from the project
    UsersProject.skip_callback(:destroy, :after, :update_repository)
    project.destroy
    UsersProject.set_callback(:destroy, :after, :update_repository)

    respond_to do |format|
      format.html { redirect_to projects_url }
    end
  end

  protected

  def project
    @project ||= Project.find_by_code(params[:id])
    @project || render_404
  end

  def determine_layout
    if @project && !@project.new_record?
      "project"
    else
      "application"
    end
  end
end

app/views/projects/_new_form.html.haml
= form_for(@project, :remote => true) do |f|
  - if @project.errors.any?
    .alert-message.block-message.error
      %span= @project.errors.full_messages.first
  .clearfix.project_name_holder
    = f.label :name do
      Project name is
    .input
      = f.text_field :name, :placeholder => "Example Project", :class => "xxlarge"
      = f.submit 'Create project', :class => "btn primary"

  %hr
  .alert.alert-info
    %h5 Advanced settings:
    .clearfix
      = f.label :path do
        Git Clone
      .input
        .input-prepend
          %span.add-on= "#{GIT_HOST["git_user"]}@#{GIT_HOST["host"]}:"
          = f.text_field :path, :placeholder => "example_project", :disabled => !@project.new_record?
          %span.add-on= ".git"
    .clearfix
      = f.label :code do
        URL
      .input
        .input-prepend
          %span.add-on= web_app_url
          = f.text_field :code, :placeholder => "example"

app/views/projects/_refs.html.haml
= form_tag switch_project_refs_path(@project), :method => :get, :class => "project-refs-form" do
  = select_tag "ref", grouped_options_refs, :onchange => "this.form.submit();", :class => "project-refs-select"
  = hidden_field_tag :destination, destination

:javascript
  $(function(){
    $('.project-refs-select').chosen();
  })

app/views/projects/_show.html.haml
%h5.title
  = @project.name
%br
%div
  %a.btn.info{:href => tree_project_ref_path(@project, @project.root_ref)} Browse code
  &nbsp;
  %a.btn{:href => project_commits_path(@project)} Commits
  %strong.right
    = link_to project_path(@project) do
      Switch to project &rarr;
%br
.alert-message.block-message.warning
  .input
    .input-prepend
      %span.add-on git clone
      = text_field_tag :project_clone, @project.url_to_repo, :class => "xlarge one_click_select git_clone_url"

= simple_format @project.description
- unless @events.blank?
  %h4.middle_title Recent Activity
  .content_list= render @events

app/views/projects/create.js.haml
- if @project.valid?
  :plain
    location.href = "#{project_path(@project, :notice => 'Project was successfully created.')}";
- else
  :plain
    $('.project_new_holder').show();
    $("#new_project").replaceWith("#{escape_javascript(render('new_form'))}");
    $('.ajax_loader').hide();

app/views/projects/edit.html.haml
= render "project_head"
.project_edit_holder
  %h3 Edit Project
  %hr
  = render "projects/form"
%div.ajax_loader.hide
  %center
    %div.padded= image_tag "ajax_loader.gif"
    %h3.prepend-top Saving project &amp; repository. Please wait...

:javascript
  $(function(){ new Projects(); });

app/views/projects/empty.html.haml
- if current_user.require_ssh_key?
  .alert-message.block-message.error
    %ul
      %li You have no ssh keys added to your profile.
      %li You wont be able to pull/push repository.
      %li Visit profile &rarr; keys and add public key of every machine you want to use for work with gitlabhq.

.alert-message.block-message.error
  %ul.unstyled.alert_holder
    %li You should push repository to proceed.
    %li After push you will be able to browse code, commits etc.

- bash_lexer = Pygments::Lexer[:bash]
%div.git-empty
  %h3 Git global setup:
  - setup_str = ["git config --global user.name \"#{current_user.name}\"",
    "git config --global user.email  \"#{current_user.email}\""].join("\n")
  = preserve do
    = raw bash_lexer.highlight(setup_str, :lexer => 'bash', :options => {:encoding => 'utf-8'})

  %br
  %br
  %h3 Create Repository
  - repo_setup_str = ["mkdir #{@project.path}",
    "cd #{@project.path}",
    "git init",
    "touch README",
    "git add README",
    "git commit -m 'first commit'",
    "git remote add origin #{@project.url_to_repo}",
    "git push -u origin master"].join("\n")

  = preserve do
    = raw bash_lexer.highlight(repo_setup_str)

  %br
  %br
  %h3 Existing Git Repo?
  - exist_repo_setup_str = ["cd existing_git_repo",
    "git remote add origin #{@project.url_to_repo}",
    "git push -u origin master"].join("\n")
  = preserve do
    = raw bash_lexer.highlight(exist_repo_setup_str)

  - if can? current_user, :admin_project, @project
    .alert-message.block-message.error.prepend-top-20
      = link_to 'Remove project', @project, :confirm => 'Are you sure?', :method => :delete, :class => "btn danger"

app/views/projects/files.html.haml
= render "project_head"
- unless @notes.empty?
  %table.zebra-striped.borders
    - @notes.each do |note|
      %tr
        %td
          %a{:href => note.attachment.url}
            = image_tag gravatar_icon(note.author_email), :class => "left", :width => 16
            &nbsp;
            = note.attachment_identifier
        %td
          Added
          = time_ago_in_words(note.created_at)
          ago
- else
  .alert-message.block-message
    %p All files attached to project wall, issues etc will be displayed here

app/views/projects/graph.html.haml
%h3 Project Network Graph
%br
.graph_holder
  %h4
    %small You can move around the graph by using arrow keys.
  #holder.graph
:javascript
  var chunk1={commits:#{@commits_json}};
  var days=#{@days_json};
  initGraph();
  $(function(){
    branchGraph($("#holder")[0]);
    initGraphNav();
  });

app/views/projects/index.html.haml
- if @projects.any?
  .projects
    .activities.span8
      - if current_user.require_ssh_key?
        .alert.alert-error.padded
          %span
            You wont be able to pull/push project code unless you
            %strong
              = link_to new_key_path, :class => "vlink" do
                add new key
            to your profile
      - if @events.any?
        = render @events
      - else
        .padded
          %strong.cgray Projects activity will be displayed here
    .side
      .projects_box
        %h5
          Projects
          %small
            (#{@projects.total_count})
          - if current_user.can_create_project?
            %span.right
              = link_to new_project_path, :class => "btn very_small info" do
                %i.icon-plus
                New Project
        - @projects.each do |project|
          = link_to project_path(project), :class => dom_class(project) do
            %h4
              %span.ico.project
              = truncate(project.name, :length => 25)
              %span.right
                &rarr;
        .bottom= paginate @projects, :theme => "gitlab"

- else
  %h3.nothing_here_message There are no projects you have access to.
  %br
  %h4.nothing_here_message
    - if current_user.can_create_project?
      You can create up to
      = current_user.projects_limit
      projects. Click on button below to add a new one
      .link_holder
        = link_to new_project_path, :class => "btn primary" do
          New Project »
    - else
      If you will be added to project - it will be displayed here

app/views/projects/index.js.haml
:plain
  Pager.append(#{@projects.count}, "#{escape_javascript(render(:partial => 'projects/tile'))}");

app/views/projects/show.html.haml
= render "project_head"

.entry
  .row
    -#.span2
      .back_link
        = link_to projects_path do
          &larr; To projects list
    .span7
      .form-horizontal
        .input-prepend
          %span.add-on git clone
          = text_field_tag :project_clone, @project.url_to_repo, :class => "one_click_select span5"
    .span4.right
      .right
        - if can? current_user, :download_code, @project
          = link_to archive_project_repository_path(@project), :class => "btn small padded" do
            %i.icon-download-alt
            Download
        - if @project.merge_requests_enabled && can?(current_user, :write_merge_request, @project)
          = link_to new_project_merge_request_path(@project), :title => "New Merge Request", :class => "btn small padded" do
            Merge Request
        - if @project.issues_enabled && can?(current_user, :write_issue, @project)
          = link_to new_project_issue_path(@project), :title => "New Issue", :class => "btn small" do
            Issue

- unless @events.blank?
  %br
  %h5.cgray
    %span.ico.activities
    Recent Activity
  %hr
  .content_list= render @events

app/views/projects/team.html.haml
= render "project_head"
%h3
  Team Members
  %small (#{@project.users_projects.count})

- if can? current_user, :admin_team_member, @project
  .alert.alert-info
    = link_to new_project_team_member_path(@project), :class => "btn small right", :title => "New Team Member" do
      New Team Member
    Read more about project permissions
    %strong= link_to "here", help_permissions_path, :class => "vlink"
    %br
    To open team member profile - click on avatar.


= render :partial => "team", :locals => {:project => @project}

app/views/projects/tree.js.haml
:plain
  $("#tree-holder table").hide("slide", { direction: "left" }, 150, function(){
    $("#tree-holder").html("#{escape_javascript(render(:partial => "tree", :locals => {:repo => @repo, :commit => @commit, :tree => @tree}))}");
    $("#tree-holder table").show("slide", { direction: "right" }, 150);
  });

app/views/projects/wall.html.haml
%div.wall_page
  = render "notes/notes", :tid => nil, :tt => "wall"